#Configuraciones de eureka-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8095

#Configuraciones de conexión a la bd
spring:
  datasource:
    username: aldo
    password: mamani
    url: jdbc:postgresql://localhost/transactionsdb
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    defer-datasource-initialization: true  

# Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    configs:
      circuitBreakerCustomer:
        slidingWindowSize: 10
        failureRateThreshold: 30
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 8
        slowCallDurationThreshold: 100ms
        slowCallRateThreshold: 50
        
    instances:
      customer-service-cb:
        base-config: circuitBreakerCustomer    