#Configuraciones de eureka-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8095

api.customer.path: http://localhost:8085/api/v1/customers/

#Configuraciones de conexión a la bd
spring:
  datasource:
    username: aldo
    password: mamani
    url: jdbc:postgresql://localhost/transactionsdb
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    defer-datasource-initialization: true  

#Configuraciones de zipkin para visualizar la trazabilidad        
management:
  tracing:
    sampling:
      probability: 1.0