#Configuraciones de eureka-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8085

#Configuraciones de conexión a la bd
spring:
  datasource:
    username: aldo
    password: mamani
    url: jdbc:mysql://mysql:3306/customersdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    defer-datasource-initialization: true    
 
 #Configuraciones de zipkin para visualizar la trazabilidad        
management:
  tracing:
    sampling:
      probability: 1.0